const people=[['a','👩🏻'],['b','👨🏽'],['c','👩🏿'],['d','👨🏻'],['e','👩🏼'],['f','👨🏾']];
const levels=[
 {name:'LEVEL 1 · RESTAURANT',intro:'Finde mit den Hinweisen heraus, wer an welchem Platz sitzt.',solution:['c','a','e','b','d','f'],clues:['👩🏿 sitzt an Tisch 1 auf Platz 1.','👩🏻 sitzt 👩🏿 an Tisch 1 gegenüber.','👩🏼 sitzt an Tisch 2 auf Platz 3.','👨🏽 sitzt 👩🏼 an Tisch 2 gegenüber.','👨🏻 sitzt an Tisch 3 auf Platz 5 und 👨🏾 gegenüber.'],offset:false},
 {name:'LEVEL 2 · RESTAURANT',intro:'Die Tische stehen diesmal versetzt. Finde wieder alle richtigen Plätze.',solution:['b','e','d','c','a','f'],clues:['👨🏽 sitzt an Tisch 1 auf Platz 1.','👩🏼 sitzt 👨🏽 gegenüber.','👨🏻 sitzt an Tisch 2 auf Platz 3.','👩🏿 sitzt 👨🏻 gegenüber.','👩🏻 sitzt an Tisch 3 auf Platz 5 und 👨🏾 gegenüber.'],offset:true}
];
let levelIndex=Math.min(Number(localStorage.getItem('platzspiel-level')||0),levels.length-1);
const board=document.querySelector('#board'),tray=document.querySelector('#tray'),status=document.querySelector('#status'),next=document.querySelector('#next');
function makeSeat(i,side){const s=document.createElement('div');s.className=`seat ${side}`;s.dataset.seat=i;s.innerHTML=`<span class="seat-num">${i+1}</span>`;return s}
function makeTable(pair,tableNo){const g=document.createElement('div');g.className='table-group';g.append(makeSeat(pair[0],'left'));const t=document.createElement('div');t.className='restaurant-table';t.textContent=`Tisch ${tableNo}`;g.append(t);g.append(makeSeat(pair[1],'right'));return g}
function makePerson([id,face]){const p=document.createElement('div');p.className='person';p.dataset.id=id;p.textContent=face;p.setAttribute('role','button');p.setAttribute('aria-label',`Figur ${face}`);bindDrag(p);return p}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function renderLevel(){const L=levels[levelIndex];document.querySelector('#sceneLabel').textContent=L.name;document.querySelector('#intro').textContent=L.intro;document.querySelector('#clues').replaceChildren(...L.clues.map(x=>{const li=document.createElement('li');li.textContent=x;return li}));board.classList.toggle('offset',L.offset);reset()}
function reset(){board.replaceChildren(makeTable([0,1],1),makeTable([2,3],2),makeTable([4,5],3));tray.replaceChildren(...shuffled(people).map(makePerson));status.textContent='';status.className='status';next.hidden=true}
function bindDrag(p){p.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;const startX=e.clientX,startY=e.clientY;const home=p.parentElement,nextSibling=p.nextSibling;let dragging=false;function begin(ev){dragging=true;p.setPointerCapture(ev.pointerId);p.classList.add('dragging');moveGhost(ev)}function moveGhost(ev){p.style.left=ev.clientX+'px';p.style.top=ev.clientY+'px'}function move(ev){const dx=ev.clientX-startX,dy=ev.clientY-startY;if(!dragging){if(Math.hypot(dx,dy)<9)return;if(Math.abs(dx)>Math.abs(dy))return cleanup();ev.preventDefault();begin(ev)}else{ev.preventDefault();moveGhost(ev)}}function end(ev){if(!dragging)return cleanup();p.classList.remove('dragging');p.style.left=p.style.top='';const under=document.elementFromPoint(ev.clientX,ev.clientY),seat=under?.closest('.seat'),solution=levels[levelIndex].solution;if(seat){const i=Number(seat.dataset.seat);if(solution[i]!==p.dataset.id){home.insertBefore(p,nextSibling);status.textContent='Dieser Platz passt nicht zu den Hinweisen.';status.className='status bad';if(navigator.vibrate)navigator.vibrate(40)}else{const occupant=seat.querySelector('.person');if(occupant&&occupant!==p)home.insertBefore(occupant,nextSibling);seat.appendChild(p);status.textContent='Richtig platziert!';status.className='status good';checkComplete()}}else if(under?.closest('.tray'))tray.appendChild(p);else home.insertBefore(p,nextSibling);cleanup()}function cancel(){if(dragging){p.classList.remove('dragging');p.style.left=p.style.top='';home.insertBefore(p,nextSibling)}cleanup()}function cleanup(){p.removeEventListener('pointermove',move);p.removeEventListener('pointerup',end);p.removeEventListener('pointercancel',cancel)}p.addEventListener('pointermove',move,{passive:false});p.addEventListener('pointerup',end);p.addEventListener('pointercancel',cancel)})}
function checkComplete(){const solution=levels[levelIndex].solution,seats=[...document.querySelectorAll('.seat')];if(seats.every((s,i)=>s.querySelector('.person')?.dataset.id===solution[i])){status.textContent=`Level ${levelIndex+1} geschafft! 🎉`;status.className='status good';if(levelIndex<levels.length-1){next.hidden=false;localStorage.setItem('platzspiel-level',String(levelIndex+1))}else{status.textContent='Alle Testlevel geschafft! 🎉';localStorage.setItem('platzspiel-level',String(levelIndex));}if(navigator.vibrate)navigator.vibrate([50,40,80])}}
document.querySelector('#reset').onclick=reset;next.onclick=()=>{if(levelIndex<levels.length-1){levelIndex++;renderLevel();window.scrollTo({top:0,behavior:'smooth'})}};
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=0.4',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));}
renderLevel();
