const people=[['a','👩🏻'],['b','👨🏽'],['c','👩🏿'],['d','👨🏻'],['e','👩🏼'],['f','👨🏾']];
const solution=['c','a','f','d','b','e'];
const board=document.querySelector('#board'),tray=document.querySelector('#tray'),status=document.querySelector('#status');
function makeSeat(i){const s=document.createElement('div');s.className='seat';s.dataset.seat=i;s.innerHTML=`<span class="seat-num">${i+1}</span>`;return s}
function makePerson([id,face]){const p=document.createElement('div');p.className='person';p.dataset.id=id;p.textContent=face;p.setAttribute('role','button');p.setAttribute('aria-label',`Figur ${face}`);bindDrag(p);return p}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function reset(){board.replaceChildren(...solution.map((_,i)=>makeSeat(i)));tray.replaceChildren(...shuffled(people).map(makePerson));status.textContent='';status.className='status'}
function bindDrag(p){p.addEventListener('pointerdown',e=>{e.preventDefault();p.setPointerCapture(e.pointerId);const home=p.parentElement,next=p.nextSibling;p.classList.add('dragging');move(e);function move(ev){p.style.left=ev.clientX+'px';p.style.top=ev.clientY+'px'}function end(ev){p.classList.remove('dragging');p.style.left=p.style.top='';const under=document.elementFromPoint(ev.clientX,ev.clientY);const seat=under?.closest('.seat');const targetPerson=under?.closest('.person');if(seat){const occupant=seat.querySelector('.person');if(occupant&&occupant!==p)home.insertBefore(occupant,next);seat.appendChild(p)}else if(under?.closest('.tray')) tray.appendChild(p);else home.insertBefore(p,next);p.removeEventListener('pointermove',move);p.removeEventListener('pointerup',end);p.removeEventListener('pointercancel',end)}p.addEventListener('pointermove',move);p.addEventListener('pointerup',end);p.addEventListener('pointercancel',end)})}
document.querySelector('#check').onclick=()=>{const seats=[...document.querySelectorAll('.seat')];if(seats.some(s=>!s.querySelector('.person'))){status.textContent='Noch sind nicht alle Stühle besetzt.';status.className='status bad';return}const ok=seats.every((s,i)=>s.querySelector('.person').dataset.id===solution[i]);status.textContent=ok?'Geschafft! Alle sitzen richtig. 🎉':'Noch nicht ganz – probiere weiter.';status.className='status '+(ok?'good':'bad')};document.querySelector('#reset').onclick=reset;if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=0.2.1',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));}reset();
